repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
      # sort imports
      - id: ruff
        args: [--select, I, --fix]
      # format
      - id: ruff-format
